name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]     # deploy whenever main updates
  workflow_dispatch: {}      # allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx tsc --pretty false   # compiles TS -> dist/
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .                     # includes index.html, app.css, dist/, etc.

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
